apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chatapp
type: Opaque
data:
  JWT: ZjI3NGE5ZWVkZTQxZWU1NmYyYzUyZGYyYmViYzc2MDBkYjMxODVhM2IzOTIxN2Q4NDE5OTM3YjllOTgwYzczM2M1YjBiZTE5YmYzMTNlMDBhZDRhNWM2ZWFiZDhmZGE0YzczYmYwMGZhYWJiYzBhMDVjNTk4ZmI2Y2IyZTQzMTRhYjA3MDJkZDc1M2Y3ZGQ2MmUwN2U4NWFhNTU1OTM0N2UwYzUwNjAwMWMyMTQ0MTc2MzUyZGY4ZTM5MmU0MzgxNWIxZjE4NDkyMTNiZGE2YTkyYTY1NDUwYTU5YTc1ZTViMGI4Njk2OWFhZWNhYTcyNzU2MWFhNGUyMjdhZjJjMzVjYTM4ZGZjMDYyZTA3ZjBlN2RmZTVkZWJmNGJlMzQxNTRiNDg3MjA4ZjIyMjM2NzUzMjAxMTdiMGFhYmQ0NWIzM2RkMzI0MmNjOThiNjkyYzIzMGNmYWVjMGMwOWEwMWM0Y2U1N2VhYjQyNDFkNDVjZmQ2MGQxNTZiODVmMjY3YzY1MGVmMjZiOWYzOThjYTEwMDhkNzlhYjJjNDhkNmVkM2YyNmZmMDI4MzMzNTYxMGRmNmRiMzUzOTM0Y2VlMmNmY2IwMGJhNzEwY2E3MTU2ZWFlNWIxZGMxMjM3MmU0YTNjYWZiYmQwOWYxNDQyNWMyMjU5NTUxYWU3YmJmYTI=
